"""Add reason debounce fields to contracts table

Revision ID: 04b8fa8820c0
Revises: 5bd3b629d09f
Create Date: 2026-03-21 17:04:39.674349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b8fa8820c0'
down_revision: Union[str, Sequence[str], None] = '5bd3b629d09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('previous_reason', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('reason_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'reason_changed_at')
    op.drop_column('contracts', 'previous_reason')
    # ### end Alembic commands ###
