"""Add bags table

Revision ID: 14314c411a15
Revises: 3e0bc8ef183f
Create Date: 2026-03-17 20:53:55.473780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14314c411a15'
down_revision: Union[str, Sequence[str], None] = '3e0bc8ef183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('bags', sa.JSON(), nullable=False),
    sa.Column('bags_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_pubkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bags')
    # ### end Alembic commands ###
