"""Replace bags table with contracts table

Revision ID: 22dc6859ebe3
Revises: 14314c411a15
Create Date: 2026-03-18 14:17:58.059472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '22dc6859ebe3'
down_revision: Union[str, Sequence[str], None] = '14314c411a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('bag_id', sa.String(length=64), nullable=False),
    sa.Column('owner_address', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('reason_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address', 'provider_pubkey')
    )
    op.create_index(op.f('ix_contracts_bag_id'), 'contracts', ['bag_id'], unique=False)
    op.create_index(op.f('ix_contracts_provider_pubkey'), 'contracts', ['provider_pubkey'], unique=False)
    op.drop_table('bags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags',
    sa.Column('provider_pubkey', sa.VARCHAR(length=64), nullable=False),
    sa.Column('bags', sqlite.JSON(), nullable=False),
    sa.Column('bags_count', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('provider_pubkey')
    )
    op.drop_index(op.f('ix_contracts_provider_pubkey'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_bag_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
