"""add indexes to history tables

Revision ID: 236edcc52cde
Revises: da34702342a0
Create Date: 2025-10-18 10:29:44.654713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236edcc52cde'
down_revision: Union[str, Sequence[str], None] = 'da34702342a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_providers_history_pubkey_archived', 'providers_history', ['pubkey', 'archived_at'], unique=False)
    op.create_index('idx_telemetry_history_pubkey_archived', 'telemetry_history', ['provider_pubkey', 'archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_history_pubkey_archived', table_name='telemetry_history')
    op.drop_index('idx_providers_history_pubkey_archived', table_name='providers_history')
    # ### end Alembic commands ###
