"""add last_online_check_time to providers

Revision ID: 3e0bc8ef183f
Revises: 68697cec4d2b
Create Date: 2025-12-12 18:16:36.993050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0bc8ef183f'
down_revision: Union[str, Sequence[str], None] = '68697cec4d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('last_online_check_time', sa.BigInteger(), nullable=True))
    op.add_column('providers_history', sa.Column('last_online_check_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers_history', 'last_online_check_time')
    op.drop_column('providers', 'last_online_check_time')
    # ### end Alembic commands ###
