"""remove telemetry_history model

Revision ID: 4c80ad9e2775
Revises: aca647250087
Create Date: 2025-08-22 22:46:39.303543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c80ad9e2775'
down_revision: Union[str, Sequence[str], None] = 'aca647250087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry.history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry.history',
    sa.Column('provider_pubkey', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_provider_space', sa.FLOAT(), nullable=False),
    sa.Column('used_provider_space', sa.FLOAT(), nullable=False),
    sa.Column('bags_count', sa.INTEGER(), nullable=False),
    sa.Column('traffic_in', sa.FLOAT(), nullable=False),
    sa.Column('traffic_out', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('provider_pubkey', 'date')
    )
    # ### end Alembic commands ###
