"""add status_ratio to provider table

Revision ID: 5929f0138a39
Revises: b0e67ae585ba
Create Date: 2025-09-05 20:11:09.729341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5929f0138a39'
down_revision: Union[str, Sequence[str], None] = 'b0e67ae585ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('status_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'status_ratio')
    # ### end Alembic commands ###
