"""Add missing_since to contracts table

Revision ID: 5bd3b629d09f
Revises: d9ec12d69856
Create Date: 2026-03-18 22:06:22.863296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd3b629d09f'
down_revision: Union[str, Sequence[str], None] = 'd9ec12d69856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'missing_since')
    # ### end Alembic commands ###
