"""refactor providers/telemetry/wallets history models

Revision ID: 68697cec4d2b
Revises: 236edcc52cde
Create Date: 2025-12-05 02:04:43.229897

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68697cec4d2b"
down_revision: Union[str, Sequence[str], None] = "236edcc52cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers_history_new",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("pubkey", sa.String(64), nullable=False),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(64), nullable=False),
        sa.Column("uptime", sa.Float(), nullable=False),
        sa.Column("status_ratio", sa.Float(), nullable=True),
        sa.Column("working_time", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("max_span", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("min_span", sa.BigInteger(), nullable=False),
        sa.Column("max_bag_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("reg_time", sa.BigInteger(), nullable=False),
        sa.Column("is_send_telemetry", sa.Boolean(), nullable=False),
        sa.Column("telemetry", sa.JSON(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.execute(
        """
        INSERT INTO providers_history_new (
            pubkey,
            location,
            status,
            address,
            uptime,
            status_ratio,
            working_time,
            rating,
            max_span,
            price,
            min_span,
            max_bag_size_bytes,
            reg_time,
            is_send_telemetry,
            telemetry,
            archived_at
        )
        SELECT
            pubkey,
            location,
            status,
            address,
            uptime,
            status_ratio,
            working_time,
            rating,
            max_span,
            price,
            min_span,
            max_bag_size_bytes,
            reg_time,
            is_send_telemetry,
            telemetry,
            archived_at
        FROM providers_history;
        """
    )

    op.drop_table("providers_history")
    op.rename_table("providers_history_new", "providers_history")

    op.create_index(
        "idx_providers_history_pubkey_archived",
        "providers_history",
        ["pubkey", "archived_at"],
        unique=False,
    )

    op.create_table(
        "telemetry_history_new",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("provider_pubkey", sa.String(64), nullable=False),
        sa.Column("bytes_recv", sa.BigInteger(), nullable=True),
        sa.Column("bytes_sent", sa.BigInteger(), nullable=True),
        sa.Column("cpu_info", sa.JSON(), nullable=True),
        sa.Column("disks_load", sa.JSON(), nullable=True),
        sa.Column("disks_load_percent", sa.JSON(), nullable=True),
        sa.Column("git_hashes", sa.JSON(), nullable=False),
        sa.Column("iops", sa.JSON(), nullable=True),
        sa.Column("net_load", sa.JSON(), nullable=True),
        sa.Column("net_recv", sa.JSON(), nullable=True),
        sa.Column("net_sent", sa.JSON(), nullable=True),
        sa.Column("pings", sa.JSON(), nullable=True),
        sa.Column("pps", sa.JSON(), nullable=True),
        sa.Column("ram", sa.JSON(), nullable=True),
        sa.Column("storage", sa.JSON(), nullable=False),
        sa.Column("swap", sa.JSON(), nullable=True),
        sa.Column("telemetry_pass", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("uname", sa.JSON(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.execute(
        """
        INSERT INTO telemetry_history_new (
            provider_pubkey,
            bytes_recv,
            bytes_sent,
            cpu_info,
            disks_load,
            disks_load_percent,
            git_hashes,
            iops,
            net_load,
            net_recv,
            net_sent,
            pings,
            pps,
            ram,
            storage,
            swap,
            telemetry_pass,
            timestamp,
            uname,
            archived_at
        )
        SELECT
            provider_pubkey,
            bytes_recv,
            bytes_sent,
            cpu_info,
            disks_load,
            disks_load_percent,
            git_hashes,
            iops,
            net_load,
            net_recv,
            net_sent,
            pings,
            pps,
            ram,
            storage,
            swap,
            telemetry_pass,
            timestamp,
            uname,
            archived_at
        FROM telemetry_history;
        """
    )

    op.drop_table("telemetry_history")
    op.rename_table("telemetry_history_new", "telemetry_history")

    op.create_index(
        "idx_telemetry_history_pubkey_archived",
        "telemetry_history",
        ["provider_pubkey", "archived_at"],
        unique=False,
    )

    op.create_table(
        "wallets_history_new",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("provider_pubkey", sa.String(64), nullable=False),
        sa.Column("address", sa.String(64), nullable=False),
        sa.Column("last_lt", sa.BigInteger(), nullable=True),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("earned", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.execute(
        """
        INSERT INTO wallets_history_new (
            provider_pubkey,
            address,
            last_lt,
            balance,
            earned,
            archived_at
        )
        SELECT
            provider_pubkey,
            address,
            last_lt,
            balance,
            earned,
            archived_at
        FROM wallets_history;
        """
    )

    op.drop_table("wallets_history")
    op.rename_table("wallets_history_new", "wallets_history")

    op.create_index(
        "idx_wallets_history_pubkey_archived",
        "wallets_history",
        ["provider_pubkey", "archived_at"],
        unique=False,
    )

    op.create_table(
        "telemetry_new",
        sa.Column("provider_pubkey", sa.String(64), primary_key=True, nullable=False),
        sa.Column("bytes_recv", sa.BigInteger(), nullable=True),
        sa.Column("bytes_sent", sa.BigInteger(), nullable=True),
        sa.Column("cpu_info", sa.JSON(), nullable=True),
        sa.Column("disks_load", sa.JSON(), nullable=True),
        sa.Column("disks_load_percent", sa.JSON(), nullable=True),
        sa.Column("git_hashes", sa.JSON(), nullable=False),
        sa.Column("iops", sa.JSON(), nullable=True),
        sa.Column("net_load", sa.JSON(), nullable=True),
        sa.Column("net_recv", sa.JSON(), nullable=True),
        sa.Column("net_sent", sa.JSON(), nullable=True),
        sa.Column("pings", sa.JSON(), nullable=True),
        sa.Column("pps", sa.JSON(), nullable=True),
        sa.Column("ram", sa.JSON(), nullable=True),
        sa.Column("storage", sa.JSON(), nullable=False),
        sa.Column("swap", sa.JSON(), nullable=True),
        sa.Column("telemetry_pass", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("uname", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute(
        """
        INSERT INTO telemetry_new (
            provider_pubkey,
            bytes_recv,
            bytes_sent,
            cpu_info,
            disks_load,
            disks_load_percent,
            git_hashes,
            iops,
            net_load,
            net_recv,
            net_sent,
            pings,
            pps,
            ram,
            storage,
            swap,
            telemetry_pass,
            timestamp,
            uname,
            updated_at
        )
        SELECT
            provider_pubkey,
            bytes_recv,
            bytes_sent,
            cpu_info,
            disks_load,
            disks_load_percent,
            git_hashes,
            iops,
            net_load,
            net_recv,
            net_sent,
            pings,
            pps,
            ram,
            storage,
            swap,
            telemetry_pass,
            timestamp,
            uname,
            updated_at
        FROM telemetry;
        """
    )

    op.drop_table("telemetry")
    op.rename_table("telemetry_new", "telemetry")

    op.create_table(
        "wallets_new",
        sa.Column("provider_pubkey", sa.String(64), primary_key=True, nullable=False),
        sa.Column("address", sa.String(64), nullable=False),
        sa.Column("last_lt", sa.BigInteger(), nullable=True),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("earned", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute(
        """
        INSERT INTO wallets_new (
            provider_pubkey,
            address,
            last_lt,
            balance,
            earned,
            updated_at
        )
        SELECT
            provider_pubkey,
            address,
            last_lt,
            balance,
            earned,
            updated_at
        FROM wallets;
        """
    )

    op.drop_table("wallets")
    op.rename_table("wallets_new", "wallets")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError("Downgrade is not supported for this migration")
