"""update telemetry table

Revision ID: 68f330b8eb20
Revises: b258d73bc69d
Create Date: 2025-08-12 13:37:53.058279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '68f330b8eb20'
down_revision: Union[str, Sequence[str], None] = 'b258d73bc69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('bytes_recv', sa.BigInteger(), nullable=True))
    op.add_column('telemetry', sa.Column('bytes_sent', sa.BigInteger(), nullable=True))
    op.add_column('telemetry', sa.Column('net_recv', sa.JSON(), nullable=True))
    op.add_column('telemetry', sa.Column('net_sent', sa.JSON(), nullable=True))
    op.add_column('telemetry', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.drop_column('telemetry', 'x_real_ip')
    op.drop_column('telemetry', 'benchmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('benchmark', sqlite.JSON(), nullable=True))
    op.add_column('telemetry', sa.Column('x_real_ip', sa.VARCHAR(), nullable=False))
    op.drop_column('telemetry', 'timestamp')
    op.drop_column('telemetry', 'net_sent')
    op.drop_column('telemetry', 'net_recv')
    op.drop_column('telemetry', 'bytes_sent')
    op.drop_column('telemetry', 'bytes_recv')
    # ### end Alembic commands ###
