"""add providers_traffic_history model

Revision ID: aca647250087
Revises: 68f330b8eb20
Create Date: 2025-08-12 18:53:46.491202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca647250087'
down_revision: Union[str, Sequence[str], None] = '68f330b8eb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers.traffic_history',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('traffic_in', sa.BigInteger(), nullable=False),
    sa.Column('traffic_out', sa.BigInteger(), nullable=False),
    sa.Column('last_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_sent', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ),
    sa.PrimaryKeyConstraint('provider_pubkey', 'date')
    )
    op.create_index('ix_traffic_history_provider_date', 'providers.traffic_history', ['provider_pubkey', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traffic_history_provider_date', table_name='providers.traffic_history')
    op.drop_table('providers.traffic_history')
    # ### end Alembic commands ###
