"""add providers_storage_history table

Revision ID: b0e67ae585ba
Revises: 4c80ad9e2775
Create Date: 2025-08-27 16:16:43.773131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e67ae585ba'
down_revision: Union[str, Sequence[str], None] = '4c80ad9e2775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers.storage_history',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_provider_space', sa.Float(), nullable=True),
    sa.Column('used_provider_space', sa.Float(), nullable=True),
    sa.Column('used_daily_space', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ),
    sa.PrimaryKeyConstraint('provider_pubkey', 'date')
    )
    op.create_index('ix_storage_history_provider_date', 'providers.storage_history', ['provider_pubkey', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_storage_history_provider_date', table_name='providers.storage_history')
    op.drop_table('providers.storage_history')
    # ### end Alembic commands ###
