"""add telemetry_pass field

Revision ID: b258d73bc69d
Revises: f56468262429
Create Date: 2025-08-11 14:39:11.425151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b258d73bc69d'
down_revision: Union[str, Sequence[str], None] = 'f56468262429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('telemetry_pass', sa.String(), nullable=True))
    op.add_column('users.subscriptions', sa.Column('telemetry_pass', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users.subscriptions', 'telemetry_pass')
    op.drop_column('telemetry', 'telemetry_pass')
    # ### end Alembic commands ###
