"""Initial schema

Revision ID: d0cae1c7c326
Revises: 
Create Date: 2025-07-28 11:37:39.621272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cae1c7c326'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('pubkey', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Float(), nullable=False),
    sa.Column('working_time', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('max_span', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('min_span', sa.BigInteger(), nullable=False),
    sa.Column('max_bag_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reg_time', sa.BigInteger(), nullable=False),
    sa.Column('is_send_telemetry', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('pubkey')
    )
    op.create_table('telemetry.history',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_provider_space', sa.Float(), nullable=False),
    sa.Column('used_provider_space', sa.Float(), nullable=False),
    sa.Column('bags_count', sa.Integer(), nullable=False),
    sa.Column('traffic_in', sa.Float(), nullable=False),
    sa.Column('traffic_out', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('provider_pubkey', 'date')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('providers.telemetry',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('storage_git_hash', sa.String(), nullable=True),
    sa.Column('provider_git_hash', sa.String(), nullable=True),
    sa.Column('qd64_disk_read_speed', sa.String(), nullable=True),
    sa.Column('qd64_disk_write_speed', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('isp', sa.String(), nullable=True),
    sa.Column('cpu_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('total_provider_space', sa.Float(), nullable=True),
    sa.Column('used_provider_space', sa.Float(), nullable=True),
    sa.Column('total_ram', sa.Float(), nullable=True),
    sa.Column('usage_ram', sa.Float(), nullable=True),
    sa.Column('ram_usage_percent', sa.Float(), nullable=True),
    sa.Column('speedtest_download', sa.Float(), nullable=True),
    sa.Column('speedtest_upload', sa.Float(), nullable=True),
    sa.Column('speedtest_ping', sa.Float(), nullable=True),
    sa.Column('cpu_number', sa.Integer(), nullable=True),
    sa.Column('cpu_is_virtual', sa.Boolean(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ),
    sa.PrimaryKeyConstraint('provider_pubkey')
    )
    op.create_table('providers.wallet_history',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('earned', sa.BigInteger(), nullable=False),
    sa.Column('last_lt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ),
    sa.PrimaryKeyConstraint('provider_pubkey', 'date')
    )
    op.create_index('ix_wallet_history_provider_date', 'providers.wallet_history', ['provider_pubkey', 'date'], unique=False)
    op.create_table('telemetry',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('storage', sa.JSON(), nullable=False),
    sa.Column('git_hashes', sa.JSON(), nullable=False),
    sa.Column('net_load', sa.JSON(), nullable=True),
    sa.Column('disks_load', sa.JSON(), nullable=True),
    sa.Column('disks_load_percent', sa.JSON(), nullable=True),
    sa.Column('iops', sa.JSON(), nullable=True),
    sa.Column('pps', sa.JSON(), nullable=True),
    sa.Column('ram', sa.JSON(), nullable=True),
    sa.Column('swap', sa.JSON(), nullable=True),
    sa.Column('uname', sa.JSON(), nullable=True),
    sa.Column('cpu_info', sa.JSON(), nullable=True),
    sa.Column('pings', sa.JSON(), nullable=True),
    sa.Column('benchmark', sa.JSON(), nullable=True),
    sa.Column('x_real_ip', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ),
    sa.PrimaryKeyConstraint('provider_pubkey')
    )
    op.create_table('users.alert_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users.alert_settings_enabled'), 'users.alert_settings', ['enabled'], unique=False)
    op.create_table('users.subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users.triggered_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_pubkey', 'alert_type', name='uq_user_provider_alert')
    )
    op.create_index(op.f('ix_users.triggered_alerts_alert_type'), 'users.triggered_alerts', ['alert_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users.triggered_alerts_alert_type'), table_name='users.triggered_alerts')
    op.drop_table('users.triggered_alerts')
    op.drop_table('users.subscriptions')
    op.drop_index(op.f('ix_users.alert_settings_enabled'), table_name='users.alert_settings')
    op.drop_table('users.alert_settings')
    op.drop_table('telemetry')
    op.drop_index('ix_wallet_history_provider_date', table_name='providers.wallet_history')
    op.drop_table('providers.wallet_history')
    op.drop_table('providers.telemetry')
    op.drop_table('users')
    op.drop_table('telemetry.history')
    op.drop_table('providers')
    # ### end Alembic commands ###
