"""Add debounce fields to users_triggered_alerts

Revision ID: d793ea79a475
Revises: 04b8fa8820c0
Create Date: 2026-04-02 14:55:29.404020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd793ea79a475'
down_revision: Union[str, Sequence[str], None] = '04b8fa8820c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_triggered_alerts', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.add_column('users_triggered_alerts', sa.Column('resolving_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_triggered_alerts', 'resolving_since')
    op.drop_column('users_triggered_alerts', 'confirmed')
    # ### end Alembic commands ###
